# This is a sample of a config file for the vision subsystem (when running
# it with the `--cfg` flag).
# The config file is in the [toml](https://github.com/toml-lang/toml) format,

[VideoSource]
# Common options:
#   - `type`: stream, oni, pcd, am_offline
# `oni` and `pcd` types require an additional parameter: file_path
# `am_offline` type requires an additional parameters: dir_path
type = "stream"
enable_rgb = false

[FilteredVideoSource]
# type = simple|prob|pt1
type = "simple"

  # The following list of filters is optional
  # The order of the filters themselves IS NOT SIGNIFICANT.
  [[FilteredVideoSource.filters]]
    type = "SensorCalibrationFilter"
    a = 1.0117
    b = -0.0100851

  [[FilteredVideoSource.filters]]
    type = "TruncateFilter"
    decimal_points = 2

# Uncomment in presense of Robot, to record pose.
# IP address and port number may differ.
# [PoseService]
# ip = 192.168.0.8
# # (The hex port value is equal to the decimal below) port = 0xd001
# port = 53249

# Available `observer` types: ObstacleDetector|SurfaceDetector|Recorder
#   ObstacleDetector requires *SplitStrategy*
#   TODO: complete description for *SurfaceDetector* requirements
#   Recorder requires RecordingOptions
[[observers]]
type = "Recorder"

  [ObserverOptions.Recorder]
  # output directory
  output_folder= "recordings"
  # Defines which data to record
  cloud = true
  rgb = false
  pose = false
